# -*- coding: utf-8 -*-
"""AIQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-0_1JopXVMsdbekqNhZUDx8CykCAHKga
"""

!pip install gspread gspread_dataframe pandas numpy

import pandas as pd
import numpy as np
import time
from datetime import datetime, timedelta
import gspread
from gspread_dataframe import set_with_dataframe

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()
gc = gspread.authorize(creds)

# Try to open your existing sheet (make sure the name matches exactly)
sheet_name = "AirQuality_Data"
try:
    sh = gc.open(sheet_name)
    worksheet = sh.sheet1
    print("✅ Connected to:", sheet_name)
except Exception as e:
    print("❌ Could not find the sheet:", e)

import random
import pandas as pd
from datetime import datetime
from gspread_dataframe import set_with_dataframe

worksheet = sh.sheet1  # Using the connected sheet

def simulate_air_quality_data():
    sensor_id = "PI5_01"
    temperature = round(random.uniform(20, 35), 2)       # in °C
    humidity = round(random.uniform(40, 90), 2)          # in %
    pm25 = round(random.uniform(10, 200), 2)             # µg/m³
    gas = round(random.uniform(100, 1000), 2)            # ppm
    ldr = random.randint(100, 1000)                      # arbitrary light intensity value
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return {
        "Timestamp": timestamp,
        "Sensor_ID": sensor_id,
        "Temperature(°C)": temperature,
        "Humidity(%)": humidity,
        "PM2.5(µg/m³)": pm25,
        "Gas(ppm)": gas,
        "LDR_Value": ldr
    }

# Create dataframe and upload multiple rows
data = [simulate_air_quality_data() for _ in range(40000)]  # simulate 10 rows
df = pd.DataFrame(data)
set_with_dataframe(worksheet, df)
print("✅ Uploaded 40000 simulated data rows to Google Sheet!")

import gspread
import pandas as pd
from google.auth import default

# 🔹 Authenticate and connect to Google Sheets
creds, _ = default()
gc = gspread.authorize(creds)

# Replace with the exact name of your Google Sheet
sheet_name = "AirQuality_Data"
worksheet = gc.open(sheet_name).sheet1

# 🔹 Get all data
data = worksheet.get_all_records()

# 🔹 Convert to pandas DataFrame
df = pd.DataFrame(data)

# Show the first few rows
print(df.head())

#PREPROCESSING

# Remove any duplicate rows
df.drop_duplicates(inplace=True)

# Check for missing values
print(df.isnull().sum())

# If any missing values exist, fill them (optional)
df.fillna(method='ffill', inplace=True)

# Convert categorical label to numeric
df['Label'] = df['Label'].map({'Safe': 0, 'Unsafe': 1})

#Verify conversion
print(df.head())

# Copy your dataframe
df_clean = df.copy()

# Create a new column "Label" based on air quality rules
df_clean['Label'] = df_clean.apply(lambda row:
    'Unsafe' if (row['PM2.5(µg/m³)'] > 80 or row['Gas(ppm)'] > 400) else 'Safe', axis=1
)

# Convert the Label to numeric for ML
df_clean['Label'] = df_clean['Label'].map({'Safe': 0, 'Unsafe': 1})

# Show few rows to confirm
print(df_clean.head())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Features and Labels
X = df_clean[['Temperature(°C)', 'Humidity(%)', 'PM2.5(µg/m³)', 'Gas(ppm)', 'LDR_Value']]
y = df_clean['Label']

# Split into train-test (80%-20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Predictions
y_pred = rf_model.predict(X_test)

# Evaluation metrics
print("✅ Model Trained Successfully!\n")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

#Live SENSOR DATA PREDICTION

import time
import pandas as pd
import numpy as np
from datetime import datetime

def simulate_live_sensor_data():
    # Create one reading (like from a live sensor)
    return {
        "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Temperature(°C)": np.random.uniform(15, 40),
        "Humidity(%)": np.random.uniform(30, 90),
        "PM2.5(µg/m³)": np.random.uniform(10, 200),
        "Gas(ppm)": np.random.uniform(100, 1000),
        "LDR_Value": np.random.uniform(100, 900)
    }

for _ in range(10):  # simulate 10 live readings
    new_data = pd.DataFrame([simulate_live_sensor_data()])
    X_live = new_data[["Temperature(°C)", "Humidity(%)", "PM2.5(µg/m³)", "Gas(ppm)", "LDR_Value"]]
    y_pred = rf_model.predict(X_live)[0]

    print(f"{new_data['Timestamp'][0]} | Prediction: {'Unsafe' if y_pred == 1 else 'Safe'}")
    time.sleep(2)

#STRAMLIT INTEGRATION

pip install streamlit

!pip install streamlit pyngrok

from pyngrok import ngrok

# Kill any previous tunnels
!kill $(ps aux | grep streamlit | awk '{print $2}') >/dev/null 2>&1

# Start the tunnel
public_url = ngrok.connect(8501)
public_url

!ngrok config add-authtoken 34jniBhF7W4sxmEVrmDAGhFOtY9_3fnj2A9rqNpUxcrQkcMy5

import threading
import time
from pyngrok import ngrok

# Kill previous streamlit if any
!kill $(ps aux | grep streamlit | awk '{print $2}') >/dev/null 2>&1

# Create a Streamlit app file
with open("app.py", "w") as f:
    f.write('''
import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime
import time

st.set_page_config(page_title="Air Quality Monitoring Dashboard", layout="wide")

st.title("🌍 Real-Time Air Quality Monitoring")
st.write("Live sensor simulation & ML prediction dashboard")

# Initialize or load data
if "data" not in st.session_state:
    st.session_state.data = pd.DataFrame(columns=["Timestamp","Temperature(°C)","Humidity(%)","PM2.5(µg/m³)","Gas(ppm)","LDR_Value","Air Quality"])

# Add new simulated data
def simulate_new_data():
    new_row = {
        "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Temperature(°C)": np.random.uniform(20, 40),
        "Humidity(%)": np.random.uniform(30, 80),
        "PM2.5(µg/m³)": np.random.uniform(5, 120),
        "Gas(ppm)": np.random.uniform(200, 900),
        "LDR_Value": np.random.uniform(100, 900),
        "Air Quality": np.random.choice(["Good", "Moderate", "Unhealthy"])
    }
    return new_row

placeholder = st.empty()

while True:
    new_data = simulate_new_data()
    st.session_state.data = pd.concat([st.session_state.data, pd.DataFrame([new_data])], ignore_index=True)

    with placeholder.container():
        st.subheader("📊 Latest Data")
        st.dataframe(st.session_state.data.tail(10), use_container_width=True)

        st.line_chart(st.session_state.data[["PM2.5(µg/m³)","Gas(ppm)","LDR_Value"]])

    time.sleep(2)
    ''')

# Run Streamlit in background
def run_streamlit():
    !streamlit run app.py --server.port 8501 >/dev/null

thread = threading.Thread(target=run_streamlit)
thread.start()

# Create tunnel
time.sleep(5)
public_url = ngrok.connect(8501)
public_url

# Overwrite the previous app.py with a more advanced dashboard
with open("app.py", "w") as f:
    f.write('''
import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime
import time

# -------------------------------
# PAGE CONFIG
# -------------------------------
st.set_page_config(page_title="Air Quality Monitoring Dashboard",
                   layout="wide",
                   page_icon="🌤️")

# -------------------------------
# SIDEBAR
# -------------------------------
st.sidebar.title("🌍 Air Quality Monitor")
st.sidebar.markdown("Real-time IoT + ML Simulation")

st.sidebar.info(
    "**Sensors Used:**\n"
    "- Temperature & Humidity (DHT11)\n"
    "- Dust/PM2.5 Sensor\n"
    "- Gas Sensor\n"
    "- LDR Sensor"
)
refresh_rate = st.sidebar.slider("⏱️ Refresh every (seconds)", 1, 10, 2)

# -------------------------------
# TITLE
# -------------------------------
st.title("🌤️ Real-Time Air Quality Dashboard")
st.markdown("Monitoring environment health using simulated IoT sensors and ML insights.")

# -------------------------------
# DATA SIMULATION
# -------------------------------
if "data" not in st.session_state:
    st.session_state.data = pd.DataFrame(columns=[
        "Timestamp", "Temperature(°C)", "Humidity(%)", "PM2.5(µg/m³)", "Gas(ppm)", "LDR_Value", "Air Quality"
    ])

def simulate_new_data():
    pm = np.random.uniform(5, 120)
    gas = np.random.uniform(200, 900)
    air_quality = "Good"
    if pm > 75 or gas > 700:
        air_quality = "Unhealthy"
    elif pm > 50 or gas > 500:
        air_quality = "Moderate"

    new_row = {
        "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Temperature(°C)": np.random.uniform(20, 40),
        "Humidity(%)": np.random.uniform(30, 80),
        "PM2.5(µg/m³)": pm,
        "Gas(ppm)": gas,
        "LDR_Value": np.random.uniform(100, 900),
        "Air Quality": air_quality
    }
    return new_row

# -------------------------------
# DASHBOARD VISUALS
# -------------------------------
placeholder = st.empty()

while True:
    new_data = simulate_new_data()
    st.session_state.data = pd.concat([st.session_state.data, pd.DataFrame([new_data])], ignore_index=True)

    with placeholder.container():
        latest = st.session_state.data.iloc[-1]

        # Top KPIs
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("🌡️ Temperature", f"{latest['Temperature(°C)']:.2f} °C")
        col2.metric("💧 Humidity", f"{latest['Humidity(%)']:.2f} %")
        col3.metric("🌫️ PM2.5", f"{latest['PM2.5(µg/m³)']:.2f} µg/m³")
        col4.metric("🔥 Gas", f"{latest['Gas(ppm)']:.2f} ppm")

        # Air Quality Status
        st.markdown("---")
        st.subheader("🧠 Air Quality Status")
        status_color = "🟢"
        if latest["Air Quality"] == "Moderate":
            status_color = "🟡"
        elif latest["Air Quality"] == "Unhealthy":
            status_color = "🔴"
        st.markdown(f"### {status_color} Current Air Quality: **{latest['Air Quality']}**")

        # Charts
        st.markdown("### 📈 Live Sensor Trends")
        chart_col1, chart_col2 = st.columns(2)
        chart_col1.line_chart(st.session_state.data[["PM2.5(µg/m³)", "Gas(ppm)"]])
        chart_col2.line_chart(st.session_state.data[["Temperature(°C)", "Humidity(%)"]])

        # Table
        st.markdown("### 📋 Recent Sensor Data")
        st.dataframe(st.session_state.data.tail(10), use_container_width=True)

    time.sleep(refresh_rate)
    ''')

print("✅ New dashboard design saved! Ready to run.")

!streamlit run app.py --server.port 8501 >/dev/null &

from pyngrok import ngrok
public_url = ngrok.connect(8501)
public_url

# Overwrite the previous app.py with fixed syntax
with open("app.py", "w") as f:
    f.write('''
import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime
import time

# -------------------------------
# PAGE CONFIG
# -------------------------------
st.set_page_config(page_title="Air Quality Monitoring Dashboard",
                   layout="wide",
                   page_icon="🌤️")

# -------------------------------
# SIDEBAR
# -------------------------------
st.sidebar.title("🌍 Air Quality Monitor")
st.sidebar.markdown("Real-time IoT + ML Simulation")

st.sidebar.info("""
**Sensors Used:**
- Temperature & Humidity (DHT11)
- Dust/PM2.5 Sensor
- Gas Sensor
- LDR Sensor
""")

refresh_rate = st.sidebar.slider("⏱️ Refresh every (seconds)", 1, 10, 2)

# -------------------------------
# TITLE
# -------------------------------
st.title("🌤️ Real-Time Air Quality Dashboard")
st.markdown("Monitoring environment health using simulated IoT sensors and ML insights.")

# -------------------------------
# DATA SIMULATION
# -------------------------------
if "data" not in st.session_state:
    st.session_state.data = pd.DataFrame(columns=[
        "Timestamp", "Temperature(°C)", "Humidity(%)", "PM2.5(µg/m³)", "Gas(ppm)", "LDR_Value", "Air Quality"
    ])

def simulate_new_data():
    pm = np.random.uniform(5, 120)
    gas = np.random.uniform(200, 900)
    air_quality = "Good"
    if pm > 75 or gas > 700:
        air_quality = "Unhealthy"
    elif pm > 50 or gas > 500:
        air_quality = "Moderate"

    new_row = {
        "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Temperature(°C)": np.random.uniform(20, 40),
        "Humidity(%)": np.random.uniform(30, 80),
        "PM2.5(µg/m³)": pm,
        "Gas(ppm)": gas,
        "LDR_Value": np.random.uniform(100, 900),
        "Air Quality": air_quality
    }
    return new_row

# -------------------------------
# DASHBOARD VISUALS
# -------------------------------
placeholder = st.empty()

while True:
    new_data = simulate_new_data()
    st.session_state.data = pd.concat([st.session_state.data, pd.DataFrame([new_data])], ignore_index=True)

    with placeholder.container():
        latest = st.session_state.data.iloc[-1]

        # Top KPIs
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("🌡️ Temperature", f"{latest['Temperature(°C)']:.2f} °C")
        col2.metric("💧 Humidity", f"{latest['Humidity(%)']:.2f} %")
        col3.metric("🌫️ PM2.5", f"{latest['PM2.5(µg/m³)']:.2f} µg/m³")
        col4.metric("🔥 Gas", f"{latest['Gas(ppm)']:.2f} ppm")

        # Air Quality Status
        st.markdown("---")
        st.subheader("🧠 Air Quality Status")
        status_color = "🟢"
        if latest["Air Quality"] == "Moderate":
            status_color = "🟡"
        elif latest["Air Quality"] == "Unhealthy":
            status_color = "🔴"
        st.markdown(f"### {status_color} Current Air Quality: **{latest['Air Quality']}**")

        # Charts
        st.markdown("### 📈 Live Sensor Trends")
        chart_col1, chart_col2 = st.columns(2)
        chart_col1.line_chart(st.session_state.data[["PM2.5(µg/m³)", "Gas(ppm)"]])
        chart_col2.line_chart(st.session_state.data[["Temperature(°C)", "Humidity(%)"]])

        # Table
        st.markdown("### 📋 Recent Sensor Data")
        st.dataframe(st.session_state.data.tail(10), use_container_width=True)

    time.sleep(refresh_rate)
    ''')

print("✅ Fixed dashboard saved! Now run Streamlit again.")

!streamlit run app.py --server.port 8501 >/dev/null &

from pyngrok import ngrok
public_url = ngrok.connect(8501)
public_url