# -*- coding: utf-8 -*-
"""Sales_Analysis(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uCL7y0XqWihCG7n1fSqmngvpxVjJsKsh
"""

import pandas as pd
df = pd.read_csv("Sales_Data(Pratice).csv")
df.head()

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Sales_Data(Pratice).csv")

# Show the first few rows
df.head()

df['Total_Sales'] = df['Units_Sold'] * df['Unit_Price']
df.head()

print(df.columns.tolist())

df.columns = df.columns.str.strip()  # removes extra spaces
df['Total_Sales'] = df['Units_Sold'] * df['Unit_Price']
df.head()

product_sales = df.groupby('Product')['Total_Sales'].sum()
print(product_sales)

best_product = product_sales.idxmax()
print("\nBest Selling Product:", best_product)

import matplotlib.pyplot as plt

product_sales.plot(kind='bar', figsize=(7,5))
plt.title("Total Sales by Product")
plt.xlabel("Product")
plt.ylabel("Total Sales (₹)")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# Pie chart for sales share
plt.figure(figsize=(6,6))
plt.pie(
    product_sales,
    labels=product_sales.index,
    autopct='%1.1f%%',
    startangle=120,
    shadow=False,
    explode=[0.00]*len(product_sales)
)
plt.title("Sales Share by Product")
plt.show()