# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3XPrSzppzn3tdTfnTT7uYl6lezHH1-m
"""

!pip install kaggle
from google.colab import files
files.upload()  # upload your kaggle.json

!mkdir ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d likhon148/animal-data
!unzip animal-data.zip -d animal_dataset

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os



import os

!ls /content



from tensorflow.keras.preprocessing.image import ImageDataGenerator

data_path = "/content/animal_dataset/animal_data"

# Split your data into 80% train and 20% validation automatically
datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_set = datagen.flow_from_directory(
    data_path,
    target_size=(128, 128),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_set = datagen.flow_from_directory(
    data_path,
    target_size=(128, 128),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2  # already splits 80/20
)

train_set = datagen.flow_from_directory(
    data_path,
    target_size=(128, 128),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_set = datagen.flow_from_directory(
    data_path,
    target_size=(128, 128),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

!ls /content/animal_dataset/animal_data

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

# --- Load base MobileNetV2 ---
base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(128, 128, 3),
    pooling='avg'   # 🩵 This fixes multiple output issue
)

# --- Build final model ---
model = Sequential([
    base_model,
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dense(15, activation='softmax')  # adjust class count
])

# Compile
model.compile(optimizer=Adam(learning_rate=0.0001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])


# 🏋️ Train model (faster than VGG16)
history = model.fit(
    datagen.flow_from_directory(data_path, target_size=(128,128), batch_size=32, subset='training'),
    validation_data=datagen.flow_from_directory(data_path, target_size=(128,128), batch_size=32, subset='validation'),
    epochs=10
)

# 💾 Save the trained model
model.save("/content/animal_classifier_mobilenetv2.keras")
print("✅ MobileNetV2 model saved successfully as animal_classifier_mobilenetv2.keras")

from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from tensorflow.keras.models import load_model

# --- 1️⃣ Upload any image ---
uploaded = files.upload()

for fn in uploaded.keys():
    img_path = fn
    print(f"✅ Uploaded: {img_path}")

# --- 2️⃣ Load the trained model (.keras file you just saved) ---
model = load_model("/content/animal_classifier_mobilenetv2.keras")

# --- 3️⃣ Correct class names (as per your dataset) ---
class_names = [
    'Bear', 'Bird', 'Cat', 'Cow', 'Deer', 'Dog', 'Dolphin', 'Elephant',
    'Giraffe', 'Horse', 'Kangaroo', 'Lion', 'Panda', 'Tiger', 'Zebra'
]

# --- 4️⃣ Preprocess uploaded image ---
img = image.load_img(img_path, target_size=(128, 128))  # same size as model training
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0) / 255.0  # normalize

# --- 5️⃣ Predict ---
predictions = model.predict(img_array)
predicted_class = class_names[np.argmax(predictions)]

# --- 6️⃣ Display result ---
plt.imshow(img)
plt.axis("off")
plt.title(f"Predicted: {predicted_class}")
plt.show()

print(f"🐾 The model predicts this image as: {predicted_class}")

model.save("animal_classifier_mobilenet_fixed.keras")

from google.colab import files
files.download('animal_classifier_mobilenet_fixed.keras')

from google.colab import drive
drive.mount('/content/drive')
!cp animal_classifier_mobilenet_fixed.keras /content/drive/MyDrive/

import os, gdown
from fastapi import FastAPI
from tensorflow.keras.models import load_model

MODEL_PATH = "animal_classifier_mobilenet_fixed.keras"
DRIVE_FILE_ID = "https://drive.google.com/file/d/1BSCstRl4ZP8xecMa3tRepvWzr5wd9PjE/view?usp=sharing"   # 🔁 replace with your own ID
DRIVE_URL = f"https://drive.google.com/uc?id={DRIVE_FILE_ID}"

app = FastAPI(title="Animal Classifier API")

# ⬇️ 1. download model if not present
if not os.path.exists(MODEL_PATH):
    print("Downloading model from Google Drive...")
    gdown.download(DRIVE_URL, MODEL_PATH, quiet=False)
    print("✅ Model downloaded successfully!")

# ⬆️ 2. load the model once
print("Loading model...")
model = load_model(MODEL_PATH)
print("✅ Model ready to use!")

@app.get("/")
def root():
    return {"status": "ok"}