# -*- coding: utf-8 -*-
"""Weather Forecasting (RandomForest).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Je_I2yJJe2ZhDe5ElcmaWNtktsNG2jz
"""

#importing Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

from google.colab import files
uploaded = files.upload()

#Loading the data set
data = pd.read_csv("weatherAUS.csv")

#handling Missing Values

data = data.dropna(subset=["RainTomorrow"])  # remove rows with no target
data.fillna(method='ffill', inplace=True)    # fill other missing values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in data.select_dtypes(include='object').columns:
    data[col] = le.fit_transform(data[col].astype(str))

X = data.drop("RainTomorrow", axis=1)
y = data["RainTomorrow"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Model Building
model = RandomForestClassifier(
    n_estimators=200,      # number of trees
    max_depth=12,          # how deep each tree can go
    random_state=42,
    n_jobs=-1              # use all CPU cores
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

#weitage Finding
importances = pd.Series(model.feature_importances_, index=X.columns)
importances.sort_values(ascending=False).head(10)